[build]
  base = "site/"
  command = "jekyll build"
  publish = "site/_site"

# Using the * -> :splat rule should redirect anything under master to the matching file under main
[[redirects]]
  from = "/docs/master/*"
  to = "/docs/main/:splat"

