disablePathToLower: true
languageCode: en-us
title: Velero
frontmatter:
  date: [":filename", ":default"]
params:
  author: Velero Authors
  vm_logo: vm-logo.png
  logo: Velero.svg
  backgroundColor: med-blue
  latest: v1.4
  gh_repo: https://github.com/vmware-tanzu/velero
  footer:
    title: Getting Started
    content: To help you get started, see the documentation.
    cta_title: ''
    cta_url: /docs
    cta_text: Documentation
    vm_link: http://vmware.github.io/
  footer_social_links:
    - title: Twitter
      fa_icon: fab fa-twitter
      url: https://twitter.com/projectvelero
    - title: Slack
      fa_icon: fab fa-slack
      url: https://kubernetes.slack.com/messages/velero
    - title: Google Groups
      fa_icon: fas fa-users
      url: https://groups.google.com/forum/#!forum/projectvelero
    - title: RSS
      fa_icon: fa fa-rss
      url: feed.xml
    - title: GitHub
      fa_icon: fab fa-github
      url: https://github.com/vmware-tanzu/velero
