blank_issues_enabled: false
contact_links:
  - name: Velero Community Support
    url: https://github.com/vmware-tanzu/velero/discussions/categories/community-support-q-a 
    about: Please ask questions about Velero here.
