---
apiVersion: ark.heptio.com/v1
kind: Config
metadata:
  namespace: heptio-ark
  name: default
persistentVolumeProvider:
  name: {{ required "PLEASE CHANGE VALUE" .Values.configuration.cloudprovider  }}
  config:
    project: {{ required "PLEASE CHANGE VALUE" .Values.configuration.project  }}
backupStorageProvider:
  name: {{ required "PLEASE CHANGE VALUE" .Values.configuration.cloudprovider  }}
  bucket: {{ required "PLEASE CHANGE VALUE" .Values.configuration.bucket  }}
backupSyncPeriod: 30m
gcSyncPeriod: 30m
scheduleSyncPeriod: 1m
restoreOnlyMode: false

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: heptio-ark
  name: ark
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: ark
    spec:
      restartPolicy: Always
      serviceAccountName: ark
      containers:
        - name: ark
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
            - /ark
          args:
            - server
          volumeMounts:
            - name: cloud-credentials
              mountPath: /credentials
            - name: plugins
              mountPath: /plugins
          env:
            - name: {{ required "PLEASE CHANGE VALUE" .Values.configuration.credentials }}
              value: /credentials/cloud
      volumes:
        - name: cloud-credentials
          secret:
            secretName: {{ .Values.secret.name }}
        - name: plugins
          emptyDir: {}
