---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    component: ark
  name: heptio-ark
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: ark
  name: ark
  namespace: heptio-ark
