apiVersion: batch/v1
kind: Job
metadata:
  name: delete-ark
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: delete-ark
    spec:
      restartPolicy: Never
      containers:
      - name: delete-ark
        image: claranet/gcloud-kubectl-docker
        imagePullPolicy: Always
        command: ["kubectl","delete","-f","/tmp/"]
        volumeMounts:
          - name: ark-server-config
            mountPath: /tmp
      volumes:
        - name: ark-server-config
          configMap:
            name: ark-server-config
      serviceAccountName: deploy-ark
